apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.wiki.secrets.credentialsSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gbf-wiki.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.wiki.secrets.onePasswordItem.path | quote }} 