# charts/gbf-wiki/templates/mediawiki-db-credentials-op-item.yaml
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.wiki.database.credentialsSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gbf-wiki.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.wiki.database.onePasswordItem.path | quote }} 