apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gbf-wiki.fullname" . }}-robots-config
  labels:
    {{- include "gbf-wiki.labels" . | nindent 4 }}
data: 
  robots.txt: |
    # gbf.wiki - please behave
    # if you feel like you've been blocked by a mistake, hit us up on our discord https://discord.gg/6WPZDFnh7w

    # please obey, these pages are pointless to scrape.
    User-agent: *
    Disallow: */edit
    Disallow: */watch
    Disallow: */unwatch
    Disallow: */delete
    Disallow: */revert
    Disallow: */rollback
    Disallow: */protect
    Disallow: */unprotect
    Disallow: */markpatrolled
    Disallow: */render
    Disallow: */submit
    Disallow: */history
    Disallow: */purge
    Disallow: */info
    Disallow: /api.php
    Disallow: /rest.php
    Disallow: /Mediawiki:
    Disallow: /Mediawiki%3A
    Disallow: /mediawiki:
    Disallow: /*?title=Mediawiki:
    Disallow: /*?title=Mediawiki%3A
    Disallow: /*?*&title=Mediawiki:
    Disallow: /*?*&title=Mediawiki%3A
    Disallow: /Property:
    Disallow: /Property%3A
    Disallow: /property:
    Disallow: /*?title=Property:
    Disallow: /*?title=Property%3A
    Disallow: /*?*&title=Property:
    Disallow: /*?*&title=Property%3A
    Disallow: /Special:
    Disallow: /Special%3A
    Disallow: /special:
    Disallow: /*?title=Special:
    Disallow: /*?title=Special%3A
    Disallow: /*?*&title=Special:
    Disallow: /*?*&title=Special%3A
    Disallow: /*?title=special:
    Disallow: /*?title=special%3A
    Disallow: /*?*&title=special:
    Disallow: /*?*&title=special%3A
    Disallow: /Talk:
    Disallow: /Talk%3A
    Disallow: /talk:
    Disallow: /*?title=Talk:
    Disallow: /*?title=Talk%3A
    Disallow: /*?*&title=Talk:
    Disallow: /*?*&title=Talk%3A
    Disallow: /*_talk:
    Disallow: /*_talk%3A
    Disallow: /*?title=*_talk:
    Disallow: /*?title=*_talk%3A
    Disallow: /*?*&title=*_talk:
    Disallow: /*?*&title=*_talk%3A
    Disallow: /Template:
    Disallow: /Template%3A
    Disallow: /template:
    Disallow: /*?title=Template:
    Disallow: /*?title=Template%3A
    Disallow: /*?*&title=Template:
    Disallow: /*?*&title=Template%3A
    Disallow: /User:
    Disallow: /User%3A
    Disallow: /User:
    Disallow: /*?title=User:
    Disallow: /*?title=User%3A
    Disallow: /*?*&title=User:
    Disallow: /*?*&title=User%3A
    Disallow: /*?action=
    Disallow: /*?*&action=
    Disallow: /*?feed=
    Disallow: /*?*&feed=
    Disallow: /*?from=
    Disallow: /*?*&from=
    Disallow: /*?oldid=
    Disallow: /*?*&oldid=
    Disallow: /*?printable=
    Disallow: /*?*&printable=
    Disallow: /*?redirect=
    Disallow: /*?*&redirect=
    Disallow: /*?uselang=
    Disallow: /*?*&uselang=
    Disallow: /*?useskin=
    Disallow: /*?*&useskin=
    Disallow: /*?veaction=
    Disallow: /*?*&veaction=
    Disallow: /*?filefrom=
    Disallow: /*?*&filefrom=
    Disallow: /*?fileuntil=
    Disallow: /*?*&fileuntil=
    Disallow: /*?navbox=
    Disallow: /*?*&navbox=
    Disallow: /*?pageuntil=
    Disallow: /*?*&pageuntil=
    Disallow: /*?pagefrom=
    Disallow: /*?*&pagefrom=
    Disallow: /*?diff=
    Disallow: /*?*&diff=
    Disallow: /*?curid=
    Disallow: /*?*&curid=
    Disallow: /*?search=
    Disallow: /*?*&search=
    Disallow: /*?section=
    Disallow: /*?*&section=
    crawl-delay: 5

    # unruly bots
    User-agent: Bytespider
    Disallow: /
    User-agent: Semrush
    Disallow: /
    User-agent: SemrushBot
    Disallow: /
    User-agent: MJ12bot
    Disallow: /
    User-agent: Mediapartners-Google*
    Disallow: /
    User-agent: UbiCrawler
    Disallow: /
    User-agent: DOC
    Disallow: /
    User-agent: Zao
    Disallow: /
    User-agent: sitecheck.internetseer.com
    Disallow: /
    User-agent: Zealbot
    Disallow: /
    User-agent: MSIECrawler
    Disallow: /
    User-agent: SiteSnagger
    Disallow: /
    User-agent: WebStripper
    Disallow: /
    User-agent: WebCopier
    Disallow: /
    User-agent: Fetch
    Disallow: /
    User-agent: Offline Explorer
    Disallow: /
    User-agent: Teleport
    Disallow: /
    User-agent: TeleportPro
    Disallow: /
    User-agent: WebZIP
    Disallow: /
    User-agent: linko
    Disallow: /
    User-agent: HTTrack
    Disallow: /
    User-agent: Microsoft.URL.Control
    Disallow: /
    User-agent: Xenu
    Disallow: /
    User-agent: larbin
    Disallow: /
    User-agent: libwww
    Disallow: /
    User-agent: ZyBORG
    Disallow: /
    User-agent: Download Ninja
    Disallow: /
    User-agent: fast
    Disallow: /
    User-agent: wget
    Disallow: /
    User-agent: grub-client
    Disallow: /
    User-agent: k2spider
    Disallow: /
    User-agent: NPBot
    Disallow: /
    User-agent: WebReaper
    Disallow: /
    User-agent: AhrefsBot
    Disallow: /
    User-agent: DotBot
    Disallow: /
    User-agent: Mauibot
    Disallow: /
    User-agent: PetalBot
    Disallow: /
    User-agent: Neevabot
    Disallow: /
    User-agent: DataForSeoBot
    Disallow: /
    User-agent: MegaIndex
    Disallow: /
    User-agent: Seekport
    Disallow: /
    User-agent: Barkrowler
    Disallow: /
    User-agent: Bytespider
    Disallow:/